using System.Collections.ObjectModel;
using System.IO;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using Launcher.App.Resources;
using Launcher.App.Services;
using Launcher.App.Utilities;
using Launcher.App.ViewModels.Shared;
using Launcher.Application.Services;
using Launcher.Domain.Models;
using Microsoft.Extensions.Logging;

namespace Launcher.App.ViewModels.Download;

public sealed partial class DownloadPageViewModel : ObservableObject
{
    private const string LocalImportCategoryId = "local_import";
    private readonly IGameVersionService gameVersionService;
    private readonly IGameInstanceService instanceService;
    private readonly DownloadTasksPageViewModel downloadTasksPage;
    private readonly IReadOnlyDictionary<LoaderKind, ILoaderProvider> loaderProviders;
    private readonly IModrinthService? modrinthService;
    private readonly IUiDispatcher uiDispatcher;
    private readonly IFloatingMessageService floatingMessageService;
    private readonly DownloadInstanceNameTracker instanceNameTracker = new();
    private bool hasLoadedVersions;
    private int refreshRequestVersion;
    private int loaderVersionRequestVersion;
    private int addonLibraryVersionRequestVersion;
    private int activeInstallCount;
    private long latestInstallSequence;
    private DownloadSourcePreference downloadSourcePreference = DownloadSourcePreference.Auto;
    private int downloadSpeedLimitMbPerSecond;
    private string lastAutoGeneratedInstanceName = string.Empty;
    private string lastLocalImportDropHintMessage = string.Empty;
    private bool isUpdatingInstanceNameInternally;

    [ObservableProperty]
    private DownloadPageStep currentStep = DownloadPageStep.VersionList;

    [ObservableProperty]
    private DownloadVersionCategory? selectedVersionCategory;

    [ObservableProperty]
    private DownloadMinecraftVersionItem? selectedMinecraftVersion;

    [ObservableProperty]
    private bool isLoadingVersions;

    [ObservableProperty]
    private string versionLoadError = string.Empty;

    [ObservableProperty]
    private string versionEmptyMessage = string.Empty;

    [ObservableProperty]
    private string versionSearchQuery = string.Empty;

    [ObservableProperty]
    private IReadOnlyList<DownloadMinecraftVersionItem> visibleVersions = Array.Empty<DownloadMinecraftVersionItem>();

    [ObservableProperty]
    private string instanceName = string.Empty;

    [ObservableProperty]
    private DownloadLoaderOption? selectedLoaderOption;

    [ObservableProperty]
    private LoaderVersionInfo? selectedLoaderVersion;

    [ObservableProperty]
    private bool isLoadingLoaderVersions;

    [ObservableProperty]
    private string loaderVersionLoadError = string.Empty;

    [ObservableProperty]
    private DownloadAddonLibraryVersionOption? selectedAddonLibraryVersion;

    [ObservableProperty]
    private bool isLoadingAddonLibraryVersions;

    [ObservableProperty]
    private string addonLibraryVersionLoadError = string.Empty;

    [ObservableProperty]
    private bool isInstalling;

    [ObservableProperty]
    private string installStatusMessage = string.Empty;

    [ObservableProperty]
    private string installError = string.Empty;

    [ObservableProperty]
    private double installProgressPercent;

    [ObservableProperty]
    private string instanceNameDuplicateMessage = string.Empty;

    [ObservableProperty]
    private int contentRefreshToken;

    [ObservableProperty]
    private int listEntranceAnimationToken;

    public DownloadPageViewModel(
        IGameVersionService gameVersionService,
        IGameInstanceService instanceService,
        DownloadTasksPageViewModel downloadTasksPage,
        IEnumerable<ILoaderProvider> loaderProviders)
        : this(
            gameVersionService,
            instanceService,
            downloadTasksPage,
            loaderProviders,
            ImmediateUiDispatcher.Instance,
            NullFloatingMessageService.Instance,
            NullInstanceFolderService.Instance,
            NullFilePickerService.Instance,
            NullLocalModpackImportService.Instance)
    {
    }

    public DownloadPageViewModel(
        IGameVersionService gameVersionService,
        IGameInstanceService instanceService,
        DownloadTasksPageViewModel downloadTasksPage,
        IEnumerable<ILoaderProvider> loaderProviders,
        IUiDispatcher uiDispatcher)
        : this(
            gameVersionService,
            instanceService,
            downloadTasksPage,
            loaderProviders,
            uiDispatcher,
            NullFloatingMessageService.Instance,
            NullInstanceFolderService.Instance,
            NullFilePickerService.Instance,
            NullLocalModpackImportService.Instance)
    {
    }

    public DownloadPageViewModel(
        IGameVersionService gameVersionService,
        IGameInstanceService instanceService,
        DownloadTasksPageViewModel downloadTasksPage,
        IEnumerable<ILoaderProvider> loaderProviders,
        IUiDispatcher uiDispatcher,
        IFloatingMessageService floatingMessageService,
        IInstanceFolderService instanceFolderService,
        IFilePickerService filePickerService,
        ILocalModpackImportService localModpackImportService,
        IModrinthService? modrinthService = null,
        ILogger<DownloadLocalImportDialogViewModel>? localImportLogger = null)
    {
        this.gameVersionService = gameVersionService;
        this.instanceService = instanceService;
        this.downloadTasksPage = downloadTasksPage;
        this.loaderProviders = loaderProviders.ToDictionary(provider => provider.Kind);
        this.modrinthService = modrinthService;
        this.uiDispatcher = uiDispatcher;
        this.floatingMessageService = floatingMessageService;
        VersionList = new DownloadVersionListViewModel(this);
        InstanceOptions = new DownloadInstanceOptionsViewModel(this);
        ModpackManualDownloadsDialog = new DownloadModpackManualDownloadsDialogViewModel(
            instanceFolderService,
            floatingMessageService);
        LocalImportDialog = new DownloadLocalImportDialogViewModel(
            filePickerService,
            localModpackImportService,
            downloadTasksPage,
            uiDispatcher,
            floatingMessageService,
            ModpackManualDownloadsDialog,
            localImportLogger);
        LocalImportDialog.ModpackImported += (_, instance) => InstanceInstalled?.Invoke(this, instance);

        LoaderVersions.CollectionChanged += (_, _) =>
        {
            OnPropertyChanged(nameof(HasLoaderVersions));
            OnPropertyChanged(nameof(HasNoLoaderVersions));
            OnPropertyChanged(nameof(LoaderVersionPlaceholderText));
        };

        AddonLibraryVersions.CollectionChanged += (_, _) =>
        {
            OnPropertyChanged(nameof(HasAddonLibraryVersions));
            OnPropertyChanged(nameof(IsAddonLibraryVersionSelectorEnabled));
            OnPropertyChanged(nameof(AddonLibraryVersionPlaceholderText));
            NotifyQuiltLibraryAliasPropertiesChanged();
        };
        ClearAddonLibraryVersionOptions();

        VersionCategories.Add(new DownloadVersionCategory("release", Strings.Download_ReleaseCategory, string.Empty, "instance_download_page/release"));
        VersionCategories.Add(new DownloadVersionCategory("snapshot", Strings.Download_SnapshotCategory, string.Empty, "instance_download_page/snapshot"));
        VersionCategories.Add(new DownloadVersionCategory("old_beta", Strings.Download_BetaCategory, "\u03b2"));
        VersionCategories.Add(new DownloadVersionCategory("old_alpha", Strings.Download_AlphaCategory, "\u03b1"));
        VersionCategories.Add(new DownloadVersionCategory(
            LocalImportCategoryId,
            Strings.Download_LocalImportCategory,
            string.Empty,
            "instance_download_page/localimport",
            isEnabled: true));

        LoaderOptions.Add(new DownloadLoaderOption(LoaderKind.Vanilla, Strings.Download_VanillaLoaderTitle, Strings.Download_VanillaLoaderSubtitle, string.Empty, "/Assets/Icons/block/grass_block.png"));
        LoaderOptions.Add(new DownloadLoaderOption(LoaderKind.Fabric, Strings.Download_FabricLoaderTitle, Strings.Download_FabricLoaderSubtitle, "\uE8B7", MinecraftVersionIconResolver.DefaultFabricIconSource));
        LoaderOptions.Add(new DownloadLoaderOption(LoaderKind.Forge, Strings.Download_ForgeLoaderTitle, Strings.Download_ForgeLoaderSubtitle, "\uE8B7", MinecraftVersionIconResolver.DefaultForgeIconSource));
        LoaderOptions.Add(new DownloadLoaderOption(LoaderKind.NeoForge, Strings.Download_NeoForgeLoaderTitle, Strings.Download_NeoForgeLoaderSubtitle, "\uE8B7", MinecraftVersionIconResolver.DefaultNeoForgeIconSource));
        LoaderOptions.Add(new DownloadLoaderOption(LoaderKind.Quilt, Strings.Download_QuiltLoaderTitle, Strings.Download_QuiltLoaderSubtitle, "\uE8B7", MinecraftVersionIconResolver.DefaultQuiltIconSource));
        SelectLoaderOptionCore(LoaderOptions.First());

        SelectVersionCategoryCore(VersionCategories.First(), deferRefresh: false);
    }

    public event EventHandler<GameInstance>? InstanceInstalled;

    public ObservableCollection<DownloadVersionCategory> VersionCategories { get; } = [];

    public ObservableCollection<DownloadLoaderOption> LoaderOptions { get; } = [];

    public ObservableCollection<LoaderVersionInfo> LoaderVersions { get; } = [];

    public ObservableCollection<DownloadAddonLibraryVersionOption> AddonLibraryVersions { get; } = [];

    public ObservableCollection<DownloadAddonLibraryVersionOption> QuiltLibraryVersions => AddonLibraryVersions;

    public List<DownloadMinecraftVersionItem> AllVersions { get; } = [];

    public DownloadVersionListViewModel VersionList { get; }

    public DownloadInstanceOptionsViewModel InstanceOptions { get; }

    public DownloadModpackManualDownloadsDialogViewModel ModpackManualDownloadsDialog { get; }

    public DownloadLocalImportDialogViewModel LocalImportDialog { get; }

    public bool HasVisibleVersions => VisibleVersions.Count > 0;

    public bool HasSelectedMinecraftVersion => SelectedMinecraftVersion is not null;

    public bool HasVersionLoadError => !string.IsNullOrWhiteSpace(VersionLoadError);

    public bool HasVersionEmptyMessage => !string.IsNullOrWhiteSpace(VersionEmptyMessage);

    public bool HasLoaderVersions => LoaderVersions.Count > 0;

    public bool HasNoLoaderVersions => !IsLoadingLoaderVersions
        && LoaderVersions.Count == 0
        && string.IsNullOrWhiteSpace(LoaderVersionLoadError)
        && RequiresLoaderVersionSelection(SelectedLoaderOption?.Kind)
        && CurrentStep is DownloadPageStep.InstanceOptions;

    public bool HasLoaderVersionLoadError => !string.IsNullOrWhiteSpace(LoaderVersionLoadError);

    public bool IsVersionListStep => CurrentStep is DownloadPageStep.VersionList;

    public bool IsInstanceOptionsStep => CurrentStep is DownloadPageStep.InstanceOptions;

    public bool IsDownloadContentVisible => IsInstanceOptionsStep || HasVisibleVersions;

    public bool HasInstallStatus => !string.IsNullOrWhiteSpace(InstallStatusMessage);

    public bool HasInstallError => !string.IsNullOrWhiteSpace(InstallError);

    public bool HasInstanceNameDuplicateMessage => !string.IsNullOrWhiteSpace(InstanceNameDuplicateMessage);

    public bool ShouldShowLoaderVersionSelector => IsInstanceOptionsStep && RequiresLoaderVersionSelection(SelectedLoaderOption?.Kind);

    public bool ShouldShowAddonLibrarySelector => IsInstanceOptionsStep && SupportsAddonLibrarySelection(SelectedLoaderOption?.Kind);

    public bool ShouldShowQuiltLibrarySelector => ShouldShowAddonLibrarySelector && SelectedLoaderOption?.Kind is LoaderKind.Quilt;

    public bool HasAddonLibraryVersions => AddonLibraryVersions.Count > 0;

    public bool HasQuiltLibraryVersions => HasAddonLibraryVersions;

    public bool HasAddonLibraryVersionLoadError => !string.IsNullOrWhiteSpace(AddonLibraryVersionLoadError);

    public bool HasQuiltLibraryVersionLoadError => HasAddonLibraryVersionLoadError;

    public bool IsAddonLibraryVersionSelectorEnabled => !IsLoadingAddonLibraryVersions && HasAddonLibraryVersions;

    public bool IsQuiltLibraryVersionSelectorEnabled => IsAddonLibraryVersionSelectorEnabled;

    public bool IsLoadingQuiltLibraryVersions => IsLoadingAddonLibraryVersions;

    public string AddonLibraryLabelText => SelectedLoaderOption?.Kind switch
    {
        LoaderKind.Fabric => Strings.Download_FabricApiLabel,
        LoaderKind.Quilt => Strings.Download_QuiltLibraryLabel,
        _ => string.Empty
    };

    public string AddonLibraryVersionPlaceholderText => IsLoadingAddonLibraryVersions
        ? Strings.Download_AddonLibraryLoading
        : HasAddonLibraryVersionLoadError
            ? Strings.Download_AddonLibraryLoadFailedShort
            : !HasAddonLibraryVersions
                ? Strings.Download_AddonLibraryEmpty
                : string.Empty;

    public string QuiltLibraryVersionPlaceholderText => AddonLibraryVersionPlaceholderText;

    public DownloadAddonLibraryVersionOption? SelectedQuiltLibraryVersion
    {
        get => SelectedAddonLibraryVersion;
        set => SelectedAddonLibraryVersion = value;
    }

    public string QuiltLibraryVersionLoadError => AddonLibraryVersionLoadError;

    public bool CanInstallSelectedVersion => CanInstall();

    public string InstallButtonText => Strings.Download_InstallButton;

    public string PageTitle => CurrentStep is DownloadPageStep.InstanceOptions
        ? SelectedMinecraftVersion?.Name ?? string.Empty
        : SelectedVersionCategory?.Title ?? string.Empty;

    public string? PageTitleIconSource => CurrentStep is DownloadPageStep.InstanceOptions
        ? SelectedMinecraftVersion?.IconSource
        : null;

    public string LoaderVersionPlaceholderText => IsLoadingLoaderVersions
        ? string.Format(Strings.Status_LoadingLoaderVersionsFormat, GetSelectedLoaderTitle())
        : !string.IsNullOrWhiteSpace(LoaderVersionLoadError)
            ? Strings.Download_LoaderVersionLoadFailedShort
            : HasNoLoaderVersions
                ? string.Format(Strings.Download_LoaderVersionEmptyFormat, GetSelectedLoaderTitle())
            : Strings.Download_SelectVersionPlaceholder;

    public void PrimeFromSettings(LauncherSettings settings)
    {
        downloadSourcePreference = settings.DownloadSourcePreference;
        downloadSpeedLimitMbPerSecond = settings.DownloadSpeedLimitMbPerSecond;
        LocalImportDialog.ApplyDownloadSourcePreference(downloadSourcePreference);
        LocalImportDialog.ApplyDownloadSpeedLimit(downloadSpeedLimitMbPerSecond);
    }

    public void ApplyDownloadSourcePreference(DownloadSourcePreference preference)
    {
        if (downloadSourcePreference == preference)
            return;

        downloadSourcePreference = preference;
        LocalImportDialog.ApplyDownloadSourcePreference(preference);
        hasLoadedVersions = false;
        IsLoadingVersions = false;
        VersionLoadError = string.Empty;
        VersionEmptyMessage = string.Empty;
        AllVersions.Clear();
        ClearSelectedVersion();
        RefreshVisibleVersions();

        if (CurrentStep is DownloadPageStep.InstanceOptions
            && RequiresLoaderVersionSelection(SelectedLoaderOption?.Kind)
            && SelectedMinecraftVersion is not null)
        {
            _ = RefreshLoaderVersionsForSelectionAsync(SelectedLoaderOption);
            _ = RefreshAddonLibraryVersionsForSelectionAsync(SelectedLoaderOption);
        }
    }

    public void ApplyDownloadSpeedLimit(int downloadSpeedLimitMbPerSecond)
    {
        this.downloadSpeedLimitMbPerSecond = Math.Max(downloadSpeedLimitMbPerSecond, 0);
        LocalImportDialog.ApplyDownloadSpeedLimit(this.downloadSpeedLimitMbPerSecond);
    }

    public bool CanHandleLocalImportDrop(IReadOnlyList<string> paths)
    {
        return CanHandleLocalImportDropCore(paths);
    }

    public bool UpdateLocalImportDropState(IReadOnlyList<string> paths)
    {
        var canAccept = CanHandleLocalImportDropCore(paths);
        ApplyLocalImportDropHint(canAccept
            ? Strings.GameSettings_DropReleaseToImportMessage
            : Strings.GameSettings_DropUnsupportedFileMessage);
        return canAccept;
    }

    public void ClearLocalImportDropState()
    {
        ApplyLocalImportDropHint(string.Empty);
    }

    public async Task<bool> HandleLocalImportDropAsync(IReadOnlyList<string> paths)
    {
        if (!CanHandleLocalImportDropCore(paths))
            return false;

        try
        {
            return await LocalImportDialog.ImportDroppedFilesAsync(paths);
        }
        finally
        {
            ClearLocalImportDropState();
        }
    }

    public async Task EnsureVersionsLoadedAsync(CancellationToken cancellationToken = default)
    {
        if (hasLoadedVersions)
            return;

        if (IsLoadingVersions)
            return;

        IsLoadingVersions = true;
        VersionLoadError = string.Empty;
        VersionEmptyMessage = string.Empty;

        try
        {
            var versions = await gameVersionService.GetVersionsAsync(
                downloadSourcePreference,
                cancellationToken,
                downloadSpeedLimitMbPerSecond);
            AllVersions.Clear();
            AllVersions.AddRange(versions.Select(version => new DownloadMinecraftVersionItem(version)));
            await RefreshExistingInstanceNamesAsync(cancellationToken);

            hasLoadedVersions = true;
        }
        catch (Exception)
        {
            VersionLoadError = Strings.Status_LoadVersionsFailed;
        }
        finally
        {
            IsLoadingVersions = false;
            RefreshVisibleVersions();
            if (hasLoadedVersions)
                ListEntranceAnimationToken++;
        }
    }

    [RelayCommand]
    private void SelectVersionCategory(DownloadVersionCategory category)
    {
        if (!category.IsEnabled)
            return;

        if (string.Equals(category.Id, LocalImportCategoryId, StringComparison.Ordinal))
        {
            LocalImportDialog.Open();
            return;
        }

        var isRefreshingCurrentCategory = ReferenceEquals(SelectedVersionCategory, category);
        SelectVersionCategoryCore(category, deferRefresh: false);

        if (isRefreshingCurrentCategory)
            RefreshCurrentCategoryContent();
        else if (hasLoadedVersions)
            ListEntranceAnimationToken++;
    }

    private void SelectVersionCategoryCore(DownloadVersionCategory category, bool deferRefresh)
    {
        SelectedVersionCategory = category;
        foreach (var item in VersionCategories)
            item.IsSelected = ReferenceEquals(item, category);

        RequestVisibleVersionsRefresh(deferRefresh);
    }

    [RelayCommand]
    private async Task SelectMinecraftVersionAsync(DownloadMinecraftVersionItem version)
    {
        SelectMinecraftVersionCore(version);
        await GoToInstanceOptions();
    }

    private void SelectMinecraftVersionCore(DownloadMinecraftVersionItem version)
    {
        SelectedMinecraftVersion = version;
        foreach (var item in AllVersions)
            item.IsSelected = ReferenceEquals(item, version);
    }

    [RelayCommand(CanExecute = nameof(CanGoToInstanceOptions))]
    private async Task GoToInstanceOptions()
    {
        if (SelectedMinecraftVersion is null)
            return;

        ResetLoaderVersionState();
        ResetAddonLibraryVersionState();
        SelectLoaderOptionCore(LoaderOptions.First(option => option.Kind is LoaderKind.Vanilla));
        ApplyAutoGeneratedInstanceName(force: true);
        await RefreshExistingInstanceNamesAsync(CancellationToken.None);
        RefreshInstanceNameDuplicateMessage();
        CurrentStep = DownloadPageStep.InstanceOptions;
    }

    private bool CanGoToInstanceOptions()
    {
        return SelectedMinecraftVersion is not null;
    }

    private bool CanHandleLocalImportDropCore(IReadOnlyList<string> paths)
    {
        if (!LocalImportDialog.CanAcceptDroppedFiles(paths))
            return false;

        var extension = Path.GetExtension(paths[0]);
        return string.Equals(extension, ".mrpack", StringComparison.OrdinalIgnoreCase)
            || string.Equals(extension, ".zip", StringComparison.OrdinalIgnoreCase);
    }

    private void ApplyLocalImportDropHint(string message)
    {
        if (string.Equals(lastLocalImportDropHintMessage, message, StringComparison.Ordinal))
            return;

        lastLocalImportDropHintMessage = message;
        floatingMessageService.Show(message);
    }

    [RelayCommand]
    private void BackToVersionList()
    {
        CurrentStep = DownloadPageStep.VersionList;
        ResetLoaderVersionState();
        ResetAddonLibraryVersionState();
        lastAutoGeneratedInstanceName = string.Empty;
        ClearSelectedVersion();
    }

    [RelayCommand]
    private void SelectLoaderOption(DownloadLoaderOption loaderOption)
    {
        SelectLoaderOptionCore(loaderOption);
    }

    private void SelectLoaderOptionCore(DownloadLoaderOption loaderOption)
    {
        SelectedLoaderOption = loaderOption;
    }

    private void RefreshCurrentCategoryContent()
    {
        CurrentStep = DownloadPageStep.VersionList;
        RequestVisibleVersionsRefresh(defer: false);
        ContentRefreshToken++;
        GoToInstanceOptionsCommand.NotifyCanExecuteChanged();
        NotifyInstallStateChanged();
    }

    [RelayCommand(CanExecute = nameof(CanInstall), AllowConcurrentExecutions = true)]
    private async Task InstallAsync()
    {
        if (!CanInstall() || SelectedMinecraftVersion is null)
            return;

        var versionName = SelectedMinecraftVersion.Name;
        var instanceName = string.IsNullOrWhiteSpace(InstanceName) ? versionName : InstanceName.Trim();
        var selectedLoader = SelectedLoaderOption ?? LoaderOptions.First(option => option.Kind is LoaderKind.Vanilla);
        var loaderVersion = selectedLoader.Kind is LoaderKind.Vanilla ? null : SelectedLoaderVersion?.Version;
        var fabricApiVersionId = selectedLoader.Kind is LoaderKind.Fabric
            ? SelectedAddonLibraryVersion?.VersionId
            : null;
        var quiltStandardLibraryVersionId = selectedLoader.Kind is LoaderKind.Quilt
            ? SelectedAddonLibraryVersion?.VersionId
            : null;
        var loaderDisplayName = GetSelectedLoaderDisplayName();
        var installSequence = Interlocked.Increment(ref latestInstallSequence);
        var installTask = downloadTasksPage.BeginTask($"{loaderDisplayName} {versionName}", instanceName);
        floatingMessageService.Show(Strings.Status_InstallStartingDownload);

        var activeInstallCountAfterStart = Interlocked.Increment(ref activeInstallCount);
        IsInstalling = activeInstallCountAfterStart > 0;
        InstallError = string.Empty;
        InstallProgressPercent = 0;
        InstallStatusMessage = Strings.Status_InstallPreparing;
        installTask.Report(new LauncherProgress(InstallProgressStages.Preparing, string.Empty, 0));
        instanceNameTracker.AddPending(instanceName);
        RefreshInstanceNameDuplicateMessage();
        CurrentStep = DownloadPageStep.VersionList;
        NotifyInstallStateChanged();
        GoToInstanceOptionsCommand.NotifyCanExecuteChanged();
        RequestVisibleVersionsRefresh(defer: true);

        try
        {
            using var installProgress = CreateProgress(installTask, installSequence);
            var instance = await instanceService.CreateInstanceAsync(
                versionName,
                selectedLoader.Kind,
                loaderVersion,
                instanceName,
                installProgress,
                installTask.CancellationToken,
                downloadSourcePreference: downloadSourcePreference,
                downloadSpeedLimitMbPerSecond: downloadSpeedLimitMbPerSecond,
                installFabricApi: fabricApiVersionId is not null,
                fabricApiVersionId: fabricApiVersionId,
                quiltStandardLibraryVersionId: quiltStandardLibraryVersionId);

            instanceNameTracker.RemovePending(instanceName);
            SetLatestInstallCompletion(installSequence, string.Format(Strings.Status_InstanceInstalledFormat, instance.Name));
            instanceNameTracker.AddExisting(instance.Name);
            instanceNameTracker.AddExisting(instance.VersionName);
            installTask.Complete(string.Format(Strings.Status_InstanceInstalledFormat, instance.Name));
            InstanceInstalled?.Invoke(this, instance);
        }
        catch (OperationCanceledException) when (installTask.IsCancellationRequested)
        {
            instanceNameTracker.RemovePending(instanceName);
            if (installSequence == latestInstallSequence)
            {
                InstallError = string.Empty;
                InstallStatusMessage = string.Empty;
                InstallProgressPercent = 0;
            }

            downloadTasksPage.CancelTask(installTask);
        }
        catch (DuplicateGameInstanceNameException)
        {
            instanceNameTracker.RemovePending(instanceName);
            SetLatestInstallFailure(installSequence, Strings.Status_DuplicateInstanceName);
            installTask.Fail(Strings.Status_DuplicateInstanceName);
        }
        catch (Exception)
        {
            instanceNameTracker.RemovePending(instanceName);
            SetLatestInstallFailure(installSequence, Strings.Status_InstallFailed);
            installTask.Fail(Strings.Status_InstallFailed);
        }
        finally
        {
            var activeInstallCountAfterFinish = Interlocked.Decrement(ref activeInstallCount);
            if (activeInstallCountAfterFinish < 0)
            {
                Interlocked.Exchange(ref activeInstallCount, 0);
                activeInstallCountAfterFinish = 0;
            }

            IsInstalling = activeInstallCountAfterFinish > 0;
            RefreshInstanceNameDuplicateMessage();
        }
    }

    private bool CanInstall()
    {
        var canInstallWithSelectedLoader = SelectedLoaderOption?.Kind switch
        {
            LoaderKind.Vanilla => true,
            { } loaderKind when RequiresLoaderVersionSelection(loaderKind) => !IsLoadingLoaderVersions
                && (!SupportsAddonLibrarySelection(loaderKind) || !IsLoadingAddonLibraryVersions)
                && string.IsNullOrWhiteSpace(LoaderVersionLoadError)
                && SelectedLoaderVersion is not null,
            _ => false
        };

        return CurrentStep is DownloadPageStep.InstanceOptions
            && SelectedMinecraftVersion is not null
            && canInstallWithSelectedLoader
            && !string.IsNullOrWhiteSpace(InstanceName)
            && !HasInstanceNameDuplicateMessage;
    }

    partial void OnSelectedLoaderOptionChanged(DownloadLoaderOption? value)
    {
        foreach (var item in LoaderOptions)
            item.IsSelected = ReferenceEquals(item, value);

        OnPropertyChanged(nameof(HasNoLoaderVersions));
        OnPropertyChanged(nameof(ShouldShowLoaderVersionSelector));
        OnPropertyChanged(nameof(ShouldShowAddonLibrarySelector));
        OnPropertyChanged(nameof(ShouldShowQuiltLibrarySelector));
        OnPropertyChanged(nameof(AddonLibraryLabelText));

        ApplyAutoGeneratedInstanceName(force: false);
        _ = RefreshLoaderVersionsForSelectionAsync(value);
        _ = RefreshAddonLibraryVersionsForSelectionAsync(value);
        NotifyInstallStateChanged();
    }

    partial void OnSelectedLoaderVersionChanged(LoaderVersionInfo? value)
    {
        ApplyAutoGeneratedInstanceName(force: false);
        NotifyInstallStateChanged();
    }

    partial void OnSelectedAddonLibraryVersionChanged(DownloadAddonLibraryVersionOption? value)
    {
        NotifyQuiltLibraryAliasPropertiesChanged();
        NotifyInstallStateChanged();
    }

    partial void OnCurrentStepChanged(DownloadPageStep value)
    {
        OnPropertyChanged(nameof(HasNoLoaderVersions));
        OnPropertyChanged(nameof(IsVersionListStep));
        OnPropertyChanged(nameof(IsInstanceOptionsStep));
        OnPropertyChanged(nameof(IsDownloadContentVisible));
        OnPropertyChanged(nameof(PageTitle));
        OnPropertyChanged(nameof(PageTitleIconSource));
        OnPropertyChanged(nameof(ShouldShowLoaderVersionSelector));
        OnPropertyChanged(nameof(ShouldShowAddonLibrarySelector));
        OnPropertyChanged(nameof(ShouldShowQuiltLibrarySelector));
        NotifyInstallStateChanged();
    }

    partial void OnSelectedVersionCategoryChanged(DownloadVersionCategory? value)
    {
        OnPropertyChanged(nameof(PageTitle));
    }

    partial void OnVersionLoadErrorChanged(string value)
    {
        OnPropertyChanged(nameof(HasVersionLoadError));
    }

    partial void OnVersionEmptyMessageChanged(string value)
    {
        OnPropertyChanged(nameof(HasVersionEmptyMessage));
    }

    partial void OnVersionSearchQueryChanged(string value)
    {
        RequestVisibleVersionsRefresh(defer: false);
    }

    partial void OnSelectedMinecraftVersionChanged(DownloadMinecraftVersionItem? value)
    {
        OnPropertyChanged(nameof(HasSelectedMinecraftVersion));
        OnPropertyChanged(nameof(PageTitle));
        OnPropertyChanged(nameof(PageTitleIconSource));
        GoToInstanceOptionsCommand.NotifyCanExecuteChanged();
        NotifyInstallStateChanged();

        if (value is null && CurrentStep is DownloadPageStep.InstanceOptions)
            CurrentStep = DownloadPageStep.VersionList;
        else if (CurrentStep is DownloadPageStep.InstanceOptions)
            _ = RefreshAddonLibraryVersionsForSelectionAsync(SelectedLoaderOption);
    }

    partial void OnVisibleVersionsChanged(IReadOnlyList<DownloadMinecraftVersionItem> value)
    {
        OnPropertyChanged(nameof(HasVisibleVersions));
        OnPropertyChanged(nameof(HasVersionEmptyMessage));
        OnPropertyChanged(nameof(IsDownloadContentVisible));
    }

    partial void OnInstanceNameChanged(string value)
    {
        RefreshInstanceNameDuplicateMessage();
        NotifyInstallStateChanged();

        if (!isUpdatingInstanceNameInternally && string.IsNullOrWhiteSpace(value?.Trim()))
            lastAutoGeneratedInstanceName = string.Empty;
    }

    partial void OnIsInstallingChanged(bool value)
    {
        NotifyInstallStateChanged();
    }

    partial void OnInstallStatusMessageChanged(string value)
    {
        OnPropertyChanged(nameof(HasInstallStatus));
    }

    partial void OnInstallErrorChanged(string value)
    {
        OnPropertyChanged(nameof(HasInstallError));
    }

    partial void OnInstanceNameDuplicateMessageChanged(string value)
    {
        OnPropertyChanged(nameof(HasInstanceNameDuplicateMessage));
        NotifyInstallStateChanged();
    }

    partial void OnIsLoadingLoaderVersionsChanged(bool value)
    {
        OnPropertyChanged(nameof(HasNoLoaderVersions));
        OnPropertyChanged(nameof(LoaderVersionPlaceholderText));
        NotifyInstallStateChanged();
    }

    partial void OnLoaderVersionLoadErrorChanged(string value)
    {
        OnPropertyChanged(nameof(HasNoLoaderVersions));
        OnPropertyChanged(nameof(HasLoaderVersionLoadError));
        OnPropertyChanged(nameof(LoaderVersionPlaceholderText));
        NotifyInstallStateChanged();
    }

    partial void OnIsLoadingAddonLibraryVersionsChanged(bool value)
    {
        OnPropertyChanged(nameof(IsAddonLibraryVersionSelectorEnabled));
        OnPropertyChanged(nameof(AddonLibraryVersionPlaceholderText));
        NotifyQuiltLibraryAliasPropertiesChanged();
        NotifyInstallStateChanged();
    }

    partial void OnAddonLibraryVersionLoadErrorChanged(string value)
    {
        OnPropertyChanged(nameof(HasAddonLibraryVersionLoadError));
        OnPropertyChanged(nameof(AddonLibraryVersionPlaceholderText));
        NotifyQuiltLibraryAliasPropertiesChanged();
    }

    private void RequestVisibleVersionsRefresh(bool defer)
    {
        var requestVersion = ++refreshRequestVersion;
        if (defer && uiDispatcher.HasAccess)
        {
            uiDispatcher.Post(
                () =>
                {
                    if (requestVersion == refreshRequestVersion)
                        RefreshVisibleVersions();
                });
            return;
        }

        RefreshVisibleVersions();
    }

    private void RefreshVisibleVersions()
    {
        var result = DownloadVersionFilter.Apply(
            AllVersions,
            SelectedVersionCategory,
            VersionSearchQuery,
            SelectedMinecraftVersion,
            hasLoadedVersions,
            IsLoadingVersions,
            HasVersionLoadError);

        VersionEmptyMessage = result.EmptyMessage;
        if (result.ShouldClearSelectedVersion)
            ClearSelectedVersion();

        SetFilteredVersions(result.Versions);
    }

    private void SetFilteredVersions(IReadOnlyList<DownloadMinecraftVersionItem> versions)
    {
        VisibleVersions = versions;
    }

    private async Task RefreshLoaderVersionsForSelectionAsync(DownloadLoaderOption? loaderOption)
    {
        if (!RequiresLoaderVersionSelection(loaderOption?.Kind)
            || SelectedMinecraftVersion is null
            || CurrentStep is not DownloadPageStep.InstanceOptions)
        {
            ResetLoaderVersionState();
            return;
        }

        if (!loaderProviders.TryGetValue(loaderOption!.Kind, out var provider) || !provider.IsImplemented)
        {
            ResetLoaderVersionState();
            OnPropertyChanged(nameof(LoaderVersionPlaceholderText));
            NotifyInstallStateChanged();
            return;
        }

        var requestVersion = ++loaderVersionRequestVersion;
        LoaderVersionLoadError = string.Empty;
        IsLoadingLoaderVersions = true;
        LoaderVersions.Clear();
        SelectedLoaderVersion = null;
        ApplyAutoGeneratedInstanceName(force: false);
        NotifyInstallStateChanged();

        try
        {
            var loaderVersions = await provider.GetLoaderVersionsAsync(
                SelectedMinecraftVersion.Name,
                downloadSourcePreference,
                downloadSpeedLimitMbPerSecond: downloadSpeedLimitMbPerSecond);
            if (!IsLoaderVersionRequestCurrent(requestVersion, loaderOption))
                return;

            LoaderVersions.ReplaceWith(loaderVersions);
            SelectedLoaderVersion = null;
            ApplyAutoGeneratedInstanceName(force: false);
        }
        catch (Exception)
        {
            if (!IsLoaderVersionRequestCurrent(requestVersion, loaderOption))
                return;

            LoaderVersionLoadError = string.Format(Strings.Status_LoaderVersionsLoadFailedFormat, loaderOption.Title);
        }
        finally
        {
            if (IsLoaderVersionRequestCurrent(requestVersion, loaderOption))
            {
                IsLoadingLoaderVersions = false;
                NotifyInstallStateChanged();
            }
        }
    }

    private async Task RefreshExistingInstanceNamesAsync(CancellationToken cancellationToken)
    {
        instanceNameTracker.ReplaceExisting(await instanceService.GetInstancesAsync(cancellationToken));
        RefreshInstanceNameDuplicateMessage();
    }

    private void RefreshInstanceNameDuplicateMessage()
    {
        InstanceNameDuplicateMessage = !string.IsNullOrWhiteSpace(InstanceName?.Trim())
            && instanceNameTracker.IsUnavailable(InstanceName)
                ? Strings.Status_DuplicateInstanceName
                : string.Empty;
    }

    private DownloadInstallProgress CreateProgress(DownloadTaskItem installTask, long installSequence)
    {
        return new DownloadInstallProgress(installTask, installSequence, ReportInstallProgress, uiDispatcher);
    }

    private void NotifyInstallStateChanged()
    {
        OnPropertyChanged(nameof(CanInstallSelectedVersion));
        InstallCommand.NotifyCanExecuteChanged();
    }

    private void NotifyQuiltLibraryAliasPropertiesChanged()
    {
        OnPropertyChanged(nameof(QuiltLibraryVersions));
        OnPropertyChanged(nameof(SelectedQuiltLibraryVersion));
        OnPropertyChanged(nameof(HasQuiltLibraryVersions));
        OnPropertyChanged(nameof(HasQuiltLibraryVersionLoadError));
        OnPropertyChanged(nameof(IsQuiltLibraryVersionSelectorEnabled));
        OnPropertyChanged(nameof(IsLoadingQuiltLibraryVersions));
        OnPropertyChanged(nameof(QuiltLibraryVersionPlaceholderText));
        OnPropertyChanged(nameof(QuiltLibraryVersionLoadError));
    }

    private void ReportInstallProgress(DownloadTaskItem installTask, LauncherProgress progress, long installSequence)
    {
        var displayProgress = CreateDisplayProgress(progress);
        if (installSequence == latestInstallSequence)
        {
            InstallError = string.Empty;
            InstallStatusMessage = displayProgress.Message;
            if (displayProgress.Percent is { } percent)
                InstallProgressPercent = percent;
        }

        installTask.Report(displayProgress);
    }

    private void SetLatestInstallCompletion(long installSequence, string message)
    {
        if (installSequence != latestInstallSequence)
            return;

        InstallError = string.Empty;
        InstallProgressPercent = 100;
        InstallStatusMessage = message;
    }

    private void SetLatestInstallFailure(long installSequence, string message)
    {
        if (installSequence != latestInstallSequence)
            return;

        InstallError = message;
        InstallStatusMessage = string.Empty;
    }

    private bool IsLoaderVersionRequestCurrent(int requestVersion, DownloadLoaderOption loaderOption)
    {
        return requestVersion == loaderVersionRequestVersion
            && ReferenceEquals(SelectedLoaderOption, loaderOption)
            && CurrentStep is DownloadPageStep.InstanceOptions;
    }

    private void ResetLoaderVersionState()
    {
        loaderVersionRequestVersion++;
        LoaderVersions.Clear();
        SelectedLoaderVersion = null;
        IsLoadingLoaderVersions = false;
        LoaderVersionLoadError = string.Empty;
        OnPropertyChanged(nameof(LoaderVersionPlaceholderText));
    }

    private async Task RefreshAddonLibraryVersionsForSelectionAsync(DownloadLoaderOption? loaderOption)
    {
        if (!SupportsAddonLibrarySelection(loaderOption?.Kind)
            || SelectedMinecraftVersion is null
            || CurrentStep is not DownloadPageStep.InstanceOptions)
        {
            ResetAddonLibraryVersionState();
            return;
        }

        var selectedLoaderOption = loaderOption!;
        var requestVersion = ++addonLibraryVersionRequestVersion;
        AddonLibraryVersionLoadError = string.Empty;
        IsLoadingAddonLibraryVersions = true;
        ClearAddonLibraryVersionOptions();

        if (modrinthService is null)
        {
            IsLoadingAddonLibraryVersions = false;
            return;
        }

        try
        {
            var versions = await GetAddonLibraryVersionsAsync(selectedLoaderOption.Kind);
            if (!IsAddonLibraryVersionRequestCurrent(requestVersion, selectedLoaderOption))
                return;

            ClearAddonLibraryVersionOptions();
            if (versions.Count > 0)
            {
                AddonLibraryVersions.Add(DownloadAddonLibraryVersionOption.None);
                var isLatest = true;
                foreach (var version in versions)
                {
                    AddonLibraryVersions.Add(DownloadAddonLibraryVersionOption.FromVersion(version, isLatest));
                    isLatest = false;
                }
            }

            SelectedAddonLibraryVersion = AddonLibraryVersions.FirstOrDefault(option => option.IsInstallable)
                ?? AddonLibraryVersions.FirstOrDefault();
        }
        catch (Exception)
        {
            if (!IsAddonLibraryVersionRequestCurrent(requestVersion, selectedLoaderOption))
                return;

            ClearAddonLibraryVersionOptions();
            AddonLibraryVersionLoadError = GetAddonLibraryVersionLoadFailedMessage(selectedLoaderOption.Kind);
        }
        finally
        {
            if (IsAddonLibraryVersionRequestCurrent(requestVersion, selectedLoaderOption))
                IsLoadingAddonLibraryVersions = false;
        }
    }

    private Task<IReadOnlyList<ModrinthVersionInfo>> GetAddonLibraryVersionsAsync(LoaderKind loaderKind)
    {
        return loaderKind switch
        {
            LoaderKind.Fabric => modrinthService!.GetFabricApiVersionsAsync(SelectedMinecraftVersion!.Name),
            LoaderKind.Quilt => modrinthService!.GetQuiltStandardLibraryVersionsAsync(SelectedMinecraftVersion!.Name),
            _ => Task.FromResult<IReadOnlyList<ModrinthVersionInfo>>([])
        };
    }

    private static string GetAddonLibraryVersionLoadFailedMessage(LoaderKind loaderKind)
    {
        return loaderKind switch
        {
            LoaderKind.Fabric => Strings.Status_FabricApiVersionsLoadFailed,
            LoaderKind.Quilt => Strings.Status_QuiltLibraryVersionsLoadFailed,
            _ => string.Empty
        };
    }

    private bool IsAddonLibraryVersionRequestCurrent(int requestVersion, DownloadLoaderOption loaderOption)
    {
        return requestVersion == addonLibraryVersionRequestVersion
            && ReferenceEquals(SelectedLoaderOption, loaderOption)
            && CurrentStep is DownloadPageStep.InstanceOptions;
    }

    private void ResetAddonLibraryVersionState()
    {
        addonLibraryVersionRequestVersion++;
        IsLoadingAddonLibraryVersions = false;
        AddonLibraryVersionLoadError = string.Empty;
        ClearAddonLibraryVersionOptions();
    }

    private void ClearAddonLibraryVersionOptions()
    {
        AddonLibraryVersions.Clear();
        SelectedAddonLibraryVersion = null;
    }

    private void ApplyAutoGeneratedInstanceName(bool force)
    {
        var suggestedName = CreateSuggestedInstanceName();
        if (string.IsNullOrWhiteSpace(suggestedName))
            return;

        var currentName = InstanceName?.Trim() ?? string.Empty;
        var shouldApply = force
            || string.IsNullOrWhiteSpace(currentName)
            || string.Equals(currentName, lastAutoGeneratedInstanceName, StringComparison.OrdinalIgnoreCase);

        if (!shouldApply)
            return;

        isUpdatingInstanceNameInternally = true;
        try
        {
            InstanceName = suggestedName;
            lastAutoGeneratedInstanceName = suggestedName;
        }
        finally
        {
            isUpdatingInstanceNameInternally = false;
        }
    }

    private string CreateSuggestedInstanceName()
    {
        var minecraftVersionName = SelectedMinecraftVersion?.Name?.Trim();
        if (string.IsNullOrWhiteSpace(minecraftVersionName))
            return string.Empty;

        return SelectedLoaderOption?.Kind switch
        {
            LoaderKind.Fabric when !string.IsNullOrWhiteSpace(SelectedLoaderVersion?.Version)
                => $"{minecraftVersionName}-fabric-{SelectedLoaderVersion.Version}",
            LoaderKind.Fabric => $"{minecraftVersionName}-fabric",
            LoaderKind.Forge when !string.IsNullOrWhiteSpace(SelectedLoaderVersion?.Version)
                => $"{minecraftVersionName}-forge-{SelectedLoaderVersion.Version}",
            LoaderKind.Forge => $"{minecraftVersionName}-forge",
            LoaderKind.NeoForge when !string.IsNullOrWhiteSpace(SelectedLoaderVersion?.Version)
                => $"{minecraftVersionName}-neoforge-{SelectedLoaderVersion.Version}",
            LoaderKind.NeoForge => $"{minecraftVersionName}-neoforge",
            LoaderKind.Quilt when !string.IsNullOrWhiteSpace(SelectedLoaderVersion?.Version)
                => $"{minecraftVersionName}-quilt-{SelectedLoaderVersion.Version}",
            LoaderKind.Quilt => $"{minecraftVersionName}-quilt",
            _ => minecraftVersionName
        };
    }

    private string GetSelectedLoaderDisplayName()
    {
        var selectedLoaderVersion = SelectedLoaderVersion?.Version;
        if (RequiresLoaderVersionSelection(SelectedLoaderOption?.Kind) && !string.IsNullOrWhiteSpace(selectedLoaderVersion))
            return $"{SelectedLoaderOption?.Title ?? Strings.Download_VanillaLoaderTitle} {selectedLoaderVersion}";

        return SelectedLoaderOption?.Title ?? Strings.Download_VanillaLoaderTitle;
    }

    private string GetSelectedLoaderTitle()
    {
        return SelectedLoaderOption?.Title ?? Strings.Download_VanillaLoaderTitle;
    }

    private static LauncherProgress CreateDisplayProgress(LauncherProgress progress)
    {
        return progress with { Message = LauncherProgressTextFormatter.Format(progress) };
    }

    private static bool RequiresLoaderVersionSelection(LoaderKind? loaderKind)
    {
        return loaderKind is LoaderKind.Fabric or LoaderKind.Forge or LoaderKind.NeoForge or LoaderKind.Quilt;
    }

    private static bool SupportsAddonLibrarySelection(LoaderKind? loaderKind)
    {
        return loaderKind is LoaderKind.Fabric or LoaderKind.Quilt;
    }

    private void ClearSelectedVersion()
    {
        SelectedMinecraftVersion = null;
        foreach (var item in AllVersions)
            item.IsSelected = false;
    }

    private sealed class NullFilePickerService : IFilePickerService
    {
        public static NullFilePickerService Instance { get; } = new();

        private NullFilePickerService()
        {
        }

        public string? PickMinecraftSkin() => null;

        public string? PickJavaExecutable() => null;

        public string? PickLocalImportFile() => null;

        public string? PickModFile() => null;

        public string? PickSaveArchive() => null;

        public string? PickResourcePackArchive() => null;

        public string? PickShaderPackArchive() => null;

        public string? PickModpackExportArchive(string defaultFileName, ModpackExportKind kind) => null;

        public string? PickFolder(string title, string? initialDirectory = null) => null;
    }

    private sealed class NullInstanceFolderService : IInstanceFolderService
    {
        public static NullInstanceFolderService Instance { get; } = new();

        private NullInstanceFolderService()
        {
        }

        public bool DirectoryExists(string folderPath) => false;

        public string EnsureDirectoryExists(string folderPath) => folderPath;

        public bool TryOpen(string folderPath) => false;

        public bool TryRevealFile(string filePath) => false;
    }

    private sealed class NullLocalModpackImportService : ILocalModpackImportService
    {
        public static NullLocalModpackImportService Instance { get; } = new();

        private NullLocalModpackImportService()
        {
        }

        public Task<ModpackRecognitionResult> RecognizeArchiveAsync(
            string archivePath,
            CancellationToken cancellationToken = default)
        {
            return Task.FromResult(ModpackRecognitionResult.Failure(ModpackRecognitionFailureReason.UnsupportedArchive));
        }

        public Task<ModpackImportResult> ImportFromArchiveAsync(
            string archivePath,
            IProgress<LauncherProgress>? progress,
            CancellationToken cancellationToken = default,
            DownloadSourcePreference downloadSourcePreference = DownloadSourcePreference.Auto,
            int downloadSpeedLimitMbPerSecond = 0)
        {
            return Task.FromResult(ModpackImportResult.Failure(ModpackImportFailureReason.UnsupportedArchive));
        }
    }

    private sealed class NullFloatingMessageService : IFloatingMessageService
    {
        public static NullFloatingMessageService Instance { get; } = new();

        public event Action<string>? MessageRequested
        {
            add { }
            remove { }
        }

        private NullFloatingMessageService()
        {
        }

        public void Show(string message)
        {
        }
    }
}
