/*
 * BlockHelm Launcher
 * Copyright (C) 2026 Quan Zhou
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 3.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 *
 * SPDX-License-Identifier: GPL-3.0-only
 */

using System.Collections.ObjectModel;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using Launcher.App.Resources;
using Launcher.App.Utilities;
using Launcher.Application.Services;
using Launcher.Domain.Models;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;

namespace Launcher.App.ViewModels.Download;

/// <summary>
/// 管理新实例安装选项、Loader/附加库异步查询、名称建议和最终请求验证。
/// </summary>
public sealed partial class DownloadInstanceOptionsViewModel : ObservableObject, IDisposable
{
    private readonly IGameInstanceService instanceService;
    // Loader 提供方只负责版本能力和安装实现；本类负责选择状态及请求世代。
    private readonly IReadOnlyDictionary<LoaderKind, ILoaderProvider> loaderProviders;
    private readonly IModrinthService? modrinthService;
    private readonly DownloadInstanceNameTracker instanceNameTracker;
    private readonly ILogger logger;
    // Loader 版本和附加库来自不同端点，独立 CTS 允许两类请求并行且互不误取消。
    private CancellationTokenSource? loaderRequestCancellation;
    private CancellationTokenSource? addonRequestCancellation;
    private DownloadMinecraftVersionItem? selectedMinecraftVersion;
    private DownloadSourcePreference downloadSourcePreference = DownloadSourcePreference.Auto;
    private int downloadSpeedLimitMbPerSecond;
    private string lastAutoGeneratedInstanceName = string.Empty;
    // 该标志区分系统建议名称和用户输入，防止属性回调把自动更新误判为手动覆盖。
    private bool isUpdatingInstanceNameInternally;
    private bool isActive;

    [ObservableProperty]
    private string instanceName = string.Empty;

    [ObservableProperty]
    private DownloadLoaderOption? selectedLoaderOption;

    [ObservableProperty]
    private LoaderVersionInfo? selectedLoaderVersion;

    [ObservableProperty]
    private bool isLoadingLoaderVersions;

    [ObservableProperty]
    private string loaderVersionLoadError = string.Empty;

    [ObservableProperty]
    private DownloadAddonLibraryVersionOption? selectedAddonLibraryVersion;

    [ObservableProperty]
    private bool isLoadingAddonLibraryVersions;

    [ObservableProperty]
    private string addonLibraryVersionLoadError = string.Empty;

    [ObservableProperty]
    private string instanceNameDuplicateMessage = string.Empty;

    internal DownloadInstanceOptionsViewModel(
        IGameInstanceService instanceService,
        IEnumerable<ILoaderProvider> loaderProviders,
        DownloadInstanceNameTracker instanceNameTracker,
        IModrinthService? modrinthService = null,
        ILogger? logger = null)
    {
        this.instanceService = instanceService;
        this.loaderProviders = loaderProviders.ToDictionary(provider => provider.Kind);
        this.instanceNameTracker = instanceNameTracker;
        this.modrinthService = modrinthService;
        this.logger = logger ?? NullLogger.Instance;
        LoaderOptions.Add(new DownloadLoaderOption(LoaderKind.Vanilla, Strings.Download_VanillaLoaderTitle, Strings.Download_VanillaLoaderSubtitle, string.Empty, "/Assets/Icons/block/grass_block.png"));
        LoaderOptions.Add(new DownloadLoaderOption(LoaderKind.Fabric, Strings.Download_FabricLoaderTitle, Strings.Download_FabricLoaderSubtitle, "\uE8B7", MinecraftVersionIconResolver.DefaultFabricIconSource));
        LoaderOptions.Add(new DownloadLoaderOption(LoaderKind.Forge, Strings.Download_ForgeLoaderTitle, Strings.Download_ForgeLoaderSubtitle, "\uE8B7", MinecraftVersionIconResolver.DefaultForgeIconSource));
        LoaderOptions.Add(new DownloadLoaderOption(LoaderKind.NeoForge, Strings.Download_NeoForgeLoaderTitle, Strings.Download_NeoForgeLoaderSubtitle, "\uE8B7", MinecraftVersionIconResolver.DefaultNeoForgeIconSource));
        LoaderOptions.Add(new DownloadLoaderOption(LoaderKind.Quilt, Strings.Download_QuiltLoaderTitle, Strings.Download_QuiltLoaderSubtitle, "\uE8B7", MinecraftVersionIconResolver.DefaultQuiltIconSource));
        LoaderVersions.CollectionChanged += (_, _) => NotifyLoaderCollectionChanged();
        AddonLibraryVersions.CollectionChanged += (_, _) => NotifyAddonCollectionChanged();
        SelectedLoaderOption = LoaderOptions[0];
    }

    public event Action? InstallAvailabilityChanged;

    public ObservableCollection<DownloadLoaderOption> LoaderOptions { get; } = [];

    public ObservableCollection<LoaderVersionInfo> LoaderVersions { get; } = [];

    public ObservableCollection<DownloadAddonLibraryVersionOption> AddonLibraryVersions { get; } = [];

    public ObservableCollection<DownloadAddonLibraryVersionOption> QuiltLibraryVersions => AddonLibraryVersions;

    public bool HasInstanceNameDuplicateMessage => !string.IsNullOrWhiteSpace(InstanceNameDuplicateMessage);

    public bool HasLoaderVersions => LoaderVersions.Count > 0;

    public bool HasNoLoaderVersions => !IsLoadingLoaderVersions
        && LoaderVersions.Count == 0
        && string.IsNullOrWhiteSpace(LoaderVersionLoadError)
        && RequiresLoaderVersionSelection(SelectedLoaderOption?.Kind)
        && isActive;

    public bool HasLoaderVersionLoadError => !string.IsNullOrWhiteSpace(LoaderVersionLoadError);

    public bool ShouldShowLoaderVersionSelector => isActive && RequiresLoaderVersionSelection(SelectedLoaderOption?.Kind);

    public bool ShouldShowAddonLibrarySelector => isActive && SupportsAddonLibrarySelection(SelectedLoaderOption?.Kind);

    public bool ShouldShowQuiltLibrarySelector => ShouldShowAddonLibrarySelector && SelectedLoaderOption?.Kind is LoaderKind.Quilt;

    public bool HasAddonLibraryVersions => AddonLibraryVersions.Count > 0;

    public bool HasQuiltLibraryVersions => HasAddonLibraryVersions;

    public bool HasAddonLibraryVersionLoadError => !string.IsNullOrWhiteSpace(AddonLibraryVersionLoadError);

    public bool HasQuiltLibraryVersionLoadError => HasAddonLibraryVersionLoadError;

    public bool IsAddonLibraryVersionSelectorEnabled => !IsLoadingAddonLibraryVersions && HasAddonLibraryVersions;

    public bool IsQuiltLibraryVersionSelectorEnabled => IsAddonLibraryVersionSelectorEnabled;

    public bool IsLoadingQuiltLibraryVersions => IsLoadingAddonLibraryVersions;

    public string AddonLibraryLabelText => SelectedLoaderOption?.Kind switch
    {
        LoaderKind.Fabric => Strings.Download_FabricApiLabel,
        LoaderKind.Quilt => Strings.Download_QuiltLibraryLabel,
        _ => string.Empty
    };

    public string LoaderVersionPlaceholderText => IsLoadingLoaderVersions
        ? string.Format(Strings.Status_LoadingLoaderVersionsFormat, GetSelectedLoaderTitle())
        : HasLoaderVersionLoadError
            ? Strings.Download_LoaderVersionLoadFailedShort
            : HasNoLoaderVersions
                ? string.Format(Strings.Download_LoaderVersionEmptyFormat, GetSelectedLoaderTitle())
                : Strings.Download_SelectVersionPlaceholder;

    public string AddonLibraryVersionPlaceholderText => IsLoadingAddonLibraryVersions
        ? Strings.Download_AddonLibraryLoading
        : HasAddonLibraryVersionLoadError
            ? Strings.Download_AddonLibraryLoadFailedShort
            : !HasAddonLibraryVersions
                ? Strings.Download_AddonLibraryEmpty
                : string.Empty;

    public string QuiltLibraryVersionPlaceholderText => AddonLibraryVersionPlaceholderText;

    public DownloadAddonLibraryVersionOption? SelectedQuiltLibraryVersion
    {
        get => SelectedAddonLibraryVersion;
        set => SelectedAddonLibraryVersion = value;
    }

    public string QuiltLibraryVersionLoadError => AddonLibraryVersionLoadError;

    public bool CanInstall => isActive
        && selectedMinecraftVersion is not null
        && CanInstallSelectedLoader()
        && !string.IsNullOrWhiteSpace(InstanceName)
        && !HasInstanceNameDuplicateMessage;

    /// <summary>
    /// 为选定 Minecraft 版本初始化安装选项，并加载实例名称占用情况。
    /// </summary>
    public async Task PrepareAsync(
        DownloadMinecraftVersionItem minecraftVersion,
        CancellationToken cancellationToken = default)
    {
        // 每次进入都从 Vanilla 基线开始，旧 Loader 选择不能泄漏到新的 Minecraft 版本。
        isActive = true;
        selectedMinecraftVersion = minecraftVersion;
        ResetLoaderVersionState();
        ResetAddonLibraryVersionState();
        SelectedLoaderOption = LoaderOptions.First(option => option.Kind is LoaderKind.Vanilla);
        ApplyAutoGeneratedInstanceName(force: true);
        await RefreshExistingInstanceNamesAsync(cancellationToken);
        NotifyStateChanged();
    }

    /// <summary>
    /// 结束当前选项会话，取消所有远端请求并清空与旧版本绑定的状态。
    /// </summary>
    public void Deactivate()
    {
        // 页面离开后所有选项结果都失去上下文，先使请求失效再清空状态，避免后台回写隐藏页面。
        isActive = false;
        selectedMinecraftVersion = null;
        CancelRequests();
        ResetLoaderVersionState();
        ResetAddonLibraryVersionState();
        lastAutoGeneratedInstanceName = string.Empty;
        NotifyStateChanged();
    }

    public void ApplyDownloadSourcePreference(DownloadSourcePreference preference)
    {
        if (downloadSourcePreference == preference)
            return;
        downloadSourcePreference = preference;
        if (isActive)
        {
            _ = RefreshLoaderVersionsForSelectionAsync(SelectedLoaderOption);
            _ = RefreshAddonLibraryVersionsForSelectionAsync(SelectedLoaderOption);
        }
    }

    public void ApplyDownloadSpeedLimit(int value)
    {
        downloadSpeedLimitMbPerSecond = Math.Max(value, 0);
    }

    /// <summary>
    /// 将已验证的页面选择冻结为安装请求；当前状态不可安装时返回空。
    /// </summary>
    public DownloadInstallRequest? CreateInstallRequest()
    {
        if (!CanInstall || selectedMinecraftVersion is null)
            return null;

        var selectedLoader = SelectedLoaderOption ?? LoaderOptions[0];
        var instanceName = string.IsNullOrWhiteSpace(InstanceName)
            ? selectedMinecraftVersion.Name
            : InstanceName.Trim();
        return new DownloadInstallRequest(
            selectedMinecraftVersion.Name,
            instanceName,
            selectedLoader.Kind,
            selectedLoader.Kind is LoaderKind.Vanilla ? null : SelectedLoaderVersion?.Version,
            selectedLoader.Kind is LoaderKind.Fabric ? SelectedAddonLibraryVersion?.VersionId : null,
            selectedLoader.Kind is LoaderKind.Quilt ? SelectedAddonLibraryVersion?.VersionId : null,
            GetSelectedLoaderDisplayName(),
            downloadSourcePreference,
            downloadSpeedLimitMbPerSecond);
    }

    public void NotifyNameAvailabilityChanged()
    {
        RefreshInstanceNameDuplicateMessage();
    }

    public void Dispose()
    {
        CancelRequests();
    }

    [RelayCommand]
    private void SelectLoaderOption(DownloadLoaderOption loaderOption)
    {
        SelectedLoaderOption = loaderOption;
    }

    partial void OnSelectedLoaderOptionChanged(DownloadLoaderOption? value)
    {
        // 集合项的 IsSelected 供模板使用，权威选择仍是 SelectedLoaderOption。
        foreach (var item in LoaderOptions)
            item.IsSelected = ReferenceEquals(item, value);
        OnPropertyChanged(nameof(HasNoLoaderVersions));
        OnPropertyChanged(nameof(ShouldShowLoaderVersionSelector));
        OnPropertyChanged(nameof(ShouldShowAddonLibrarySelector));
        OnPropertyChanged(nameof(ShouldShowQuiltLibrarySelector));
        OnPropertyChanged(nameof(AddonLibraryLabelText));
        // Loader 变化会影响建议名称和两类远端版本，但请求可并行启动。
        ApplyAutoGeneratedInstanceName(force: false);
        // 两类版本来自独立数据源并可并行刷新，各自用独立 CTS 保证最后一次选择生效。
        _ = RefreshLoaderVersionsForSelectionAsync(value);
        _ = RefreshAddonLibraryVersionsForSelectionAsync(value);
        NotifyStateChanged();
    }

    partial void OnSelectedLoaderVersionChanged(LoaderVersionInfo? value)
    {
        ApplyAutoGeneratedInstanceName(force: false);
        NotifyStateChanged();
    }

    partial void OnSelectedAddonLibraryVersionChanged(DownloadAddonLibraryVersionOption? value)
    {
        NotifyQuiltLibraryAliasPropertiesChanged();
        NotifyStateChanged();
    }

    partial void OnInstanceNameChanged(string value)
    {
        RefreshInstanceNameDuplicateMessage();
        if (!isUpdatingInstanceNameInternally && string.IsNullOrWhiteSpace(value?.Trim()))
            lastAutoGeneratedInstanceName = string.Empty;
        NotifyStateChanged();
    }

    partial void OnInstanceNameDuplicateMessageChanged(string value)
    {
        OnPropertyChanged(nameof(HasInstanceNameDuplicateMessage));
        NotifyStateChanged();
    }

    partial void OnIsLoadingLoaderVersionsChanged(bool value)
    {
        OnPropertyChanged(nameof(HasNoLoaderVersions));
        OnPropertyChanged(nameof(LoaderVersionPlaceholderText));
        NotifyStateChanged();
    }

    partial void OnLoaderVersionLoadErrorChanged(string value)
    {
        OnPropertyChanged(nameof(HasNoLoaderVersions));
        OnPropertyChanged(nameof(HasLoaderVersionLoadError));
        OnPropertyChanged(nameof(LoaderVersionPlaceholderText));
        NotifyStateChanged();
    }

    partial void OnIsLoadingAddonLibraryVersionsChanged(bool value)
    {
        OnPropertyChanged(nameof(IsAddonLibraryVersionSelectorEnabled));
        OnPropertyChanged(nameof(AddonLibraryVersionPlaceholderText));
        NotifyQuiltLibraryAliasPropertiesChanged();
        NotifyStateChanged();
    }

    partial void OnAddonLibraryVersionLoadErrorChanged(string value)
    {
        OnPropertyChanged(nameof(HasAddonLibraryVersionLoadError));
        OnPropertyChanged(nameof(AddonLibraryVersionPlaceholderText));
        NotifyQuiltLibraryAliasPropertiesChanged();
    }

    /// <summary>
    /// 获取当前 Loader 可用版本，且只允许仍匹配当前页面选择的请求更新集合。
    /// </summary>
    private async Task RefreshLoaderVersionsForSelectionAsync(DownloadLoaderOption? loaderOption)
    {
        // 除取消标记外还校验 loader 与 Minecraft 版本，覆盖提供方忽略 CancellationToken 的情况。
        var cancellation = ReplaceLoaderRequestCancellation();
        if (!RequiresLoaderVersionSelection(loaderOption?.Kind)
            || selectedMinecraftVersion is null
            || !isActive)
        {
            ResetLoaderVersionState(cancelRequest: false);
            ReleaseLoaderCancellation(cancellation);
            return;
        }

        if (!loaderProviders.TryGetValue(loaderOption!.Kind, out var provider) || !provider.IsImplemented)
        {
            ResetLoaderVersionState(cancelRequest: false);
            ReleaseLoaderCancellation(cancellation);
            return;
        }

        var requestedVersion = selectedMinecraftVersion.Name;
        LoaderVersionLoadError = string.Empty;
        IsLoadingLoaderVersions = true;
        LoaderVersions.Clear();
        SelectedLoaderVersion = null;
        try
        {
            var versions = await provider.GetLoaderVersionsAsync(
                requestedVersion,
                downloadSourcePreference,
                cancellation.Token,
                downloadSpeedLimitMbPerSecond);
            // 提供方可能在取消后仍返回，因此还要比对 CTS、Loader 对象和 Minecraft 版本。
            if (!IsLoaderRequestCurrent(cancellation, loaderOption, requestedVersion))
                return;
            LoaderVersions.ReplaceWith(versions);
            SelectedLoaderVersion = null;
            ApplyAutoGeneratedInstanceName(force: false);
        }
        catch (OperationCanceledException) when (cancellation.IsCancellationRequested)
        {
        }
        catch (Exception exception)
        {
            logger.LogWarning(
                exception,
                "Failed to load loader versions. MinecraftVersion={MinecraftVersion} Loader={Loader}",
                requestedVersion,
                loaderOption.Kind);
            if (IsLoaderRequestCurrent(cancellation, loaderOption, requestedVersion))
                LoaderVersionLoadError = string.Format(Strings.Status_LoaderVersionsLoadFailedFormat, loaderOption.Title);
        }
        finally
        {
            if (IsLoaderRequestCurrent(cancellation, loaderOption, requestedVersion))
                IsLoadingLoaderVersions = false;
            ReleaseLoaderCancellation(cancellation);
        }
    }

    /// <summary>
    /// 获取 Fabric API 或 Quilt 标准库版本，并为“无需安装”保留显式选项。
    /// </summary>
    private async Task RefreshAddonLibraryVersionsForSelectionAsync(DownloadLoaderOption? loaderOption)
    {
        // 可选库刷新与 loader 列表互不占用取消源，防止一个请求完成时误释放另一个请求。
        var cancellation = ReplaceAddonRequestCancellation();
        if (!SupportsAddonLibrarySelection(loaderOption?.Kind)
            || selectedMinecraftVersion is null
            || !isActive)
        {
            ResetAddonLibraryVersionState(cancelRequest: false);
            ReleaseAddonCancellation(cancellation);
            return;
        }

        var requestedVersion = selectedMinecraftVersion.Name;
        AddonLibraryVersionLoadError = string.Empty;
        IsLoadingAddonLibraryVersions = true;
        ClearAddonLibraryVersionOptions();
        if (modrinthService is null)
        {
            IsLoadingAddonLibraryVersions = false;
            ReleaseAddonCancellation(cancellation);
            return;
        }

        try
        {
            var versions = await GetAddonLibraryVersionsAsync(loaderOption!.Kind, requestedVersion, cancellation.Token);
            if (!IsAddonRequestCurrent(cancellation, loaderOption, requestedVersion))
                return;
            // “不安装附加库”必须是明确选项，不能用 null 同时表示加载中和用户不安装。
            AddonLibraryVersions.Add(DownloadAddonLibraryVersionOption.None);
            var isLatest = true;
            foreach (var version in versions)
            {
                AddonLibraryVersions.Add(DownloadAddonLibraryVersionOption.FromVersion(version, isLatest));
                isLatest = false;
            }

            SelectedAddonLibraryVersion = AddonLibraryVersions.FirstOrDefault(option => option.IsInstallable)
                ?? AddonLibraryVersions.FirstOrDefault();
        }
        catch (OperationCanceledException) when (cancellation.IsCancellationRequested)
        {
        }
        catch (Exception exception)
        {
            logger.LogWarning(
                exception,
                "Failed to load optional loader library versions. MinecraftVersion={MinecraftVersion} Loader={Loader}",
                requestedVersion,
                loaderOption!.Kind);
            if (IsAddonRequestCurrent(cancellation, loaderOption!, requestedVersion))
            {
                ClearAddonLibraryVersionOptions();
                AddonLibraryVersionLoadError = GetAddonLibraryVersionLoadFailedMessage(loaderOption!.Kind);
            }
        }
        finally
        {
            if (IsAddonRequestCurrent(cancellation, loaderOption!, requestedVersion))
                IsLoadingAddonLibraryVersions = false;
            ReleaseAddonCancellation(cancellation);
        }
    }

    private async Task RefreshExistingInstanceNamesAsync(CancellationToken cancellationToken)
    {
        instanceNameTracker.ReplaceExisting(await instanceService.GetInstancesAsync(cancellationToken));
        RefreshInstanceNameDuplicateMessage();
    }

    private void RefreshInstanceNameDuplicateMessage()
    {
        InstanceNameDuplicateMessage = !string.IsNullOrWhiteSpace(InstanceName?.Trim())
            && instanceNameTracker.IsUnavailable(InstanceName)
                ? Strings.Status_DuplicateInstanceName
                : string.Empty;
    }

    /// <summary>
    /// 仅在名称仍由系统管理时更新建议名称，避免覆盖用户手动输入。
    /// </summary>
    private void ApplyAutoGeneratedInstanceName(bool force)
    {
        var suggestedName = CreateSuggestedInstanceName();
        if (string.IsNullOrWhiteSpace(suggestedName))
            return;
        var currentName = InstanceName?.Trim() ?? string.Empty;
        // 只有强制初始化、空名称或仍等于上次建议值时才允许系统接管名称。
        if (!force
            && !string.IsNullOrWhiteSpace(currentName)
            && !string.Equals(currentName, lastAutoGeneratedInstanceName, StringComparison.OrdinalIgnoreCase))
        {
            return;
        }

        // 属性回调会同步执行，用 try/finally 保证异常时也不会永久进入“内部更新”状态。
        isUpdatingInstanceNameInternally = true;
        try
        {
            InstanceName = suggestedName;
            lastAutoGeneratedInstanceName = suggestedName;
        }
        finally
        {
            isUpdatingInstanceNameInternally = false;
        }
    }

    private string CreateSuggestedInstanceName()
    {
        var minecraftVersion = selectedMinecraftVersion?.Name?.Trim();
        if (string.IsNullOrWhiteSpace(minecraftVersion))
            return string.Empty;
        var loaderVersion = SelectedLoaderVersion?.Version;
        return SelectedLoaderOption?.Kind switch
        {
            LoaderKind.Fabric when !string.IsNullOrWhiteSpace(loaderVersion) => $"{minecraftVersion}-fabric-{loaderVersion}",
            LoaderKind.Fabric => $"{minecraftVersion}-fabric",
            LoaderKind.Forge when !string.IsNullOrWhiteSpace(loaderVersion) => $"{minecraftVersion}-forge-{loaderVersion}",
            LoaderKind.Forge => $"{minecraftVersion}-forge",
            LoaderKind.NeoForge when !string.IsNullOrWhiteSpace(loaderVersion) => $"{minecraftVersion}-neoforge-{loaderVersion}",
            LoaderKind.NeoForge => $"{minecraftVersion}-neoforge",
            LoaderKind.Quilt when !string.IsNullOrWhiteSpace(loaderVersion) => $"{minecraftVersion}-quilt-{loaderVersion}",
            LoaderKind.Quilt => $"{minecraftVersion}-quilt",
            _ => minecraftVersion
        };
    }

    private bool CanInstallSelectedLoader()
    {
        return SelectedLoaderOption?.Kind switch
        {
            LoaderKind.Vanilla => true,
            { } kind when RequiresLoaderVersionSelection(kind) => !IsLoadingLoaderVersions
                && (!SupportsAddonLibrarySelection(kind) || !IsLoadingAddonLibraryVersions)
                && string.IsNullOrWhiteSpace(LoaderVersionLoadError)
                && SelectedLoaderVersion is not null,
            _ => false
        };
    }

    private string GetSelectedLoaderDisplayName()
    {
        var version = SelectedLoaderVersion?.Version;
        if (RequiresLoaderVersionSelection(SelectedLoaderOption?.Kind) && !string.IsNullOrWhiteSpace(version))
            return $"{GetSelectedLoaderTitle()} {version}";
        return GetSelectedLoaderTitle();
    }

    private string GetSelectedLoaderTitle() => SelectedLoaderOption?.Title ?? Strings.Download_VanillaLoaderTitle;

    private Task<IReadOnlyList<ModrinthVersionInfo>> GetAddonLibraryVersionsAsync(
        LoaderKind loaderKind,
        string minecraftVersion,
        CancellationToken cancellationToken)
    {
        return loaderKind switch
        {
            LoaderKind.Fabric => modrinthService!.GetFabricApiVersionsAsync(minecraftVersion, cancellationToken),
            LoaderKind.Quilt => modrinthService!.GetQuiltStandardLibraryVersionsAsync(minecraftVersion, cancellationToken),
            _ => Task.FromResult<IReadOnlyList<ModrinthVersionInfo>>([])
        };
    }

    private static string GetAddonLibraryVersionLoadFailedMessage(LoaderKind loaderKind)
    {
        return loaderKind switch
        {
            LoaderKind.Fabric => Strings.Status_FabricApiVersionsLoadFailed,
            LoaderKind.Quilt => Strings.Status_QuiltLibraryVersionsLoadFailed,
            _ => string.Empty
        };
    }

    private CancellationTokenSource ReplaceLoaderRequestCancellation()
    {
        var next = new CancellationTokenSource();
        var previous = Interlocked.Exchange(ref loaderRequestCancellation, next);
        previous?.Cancel();
        return next;
    }

    private CancellationTokenSource ReplaceAddonRequestCancellation()
    {
        var next = new CancellationTokenSource();
        var previous = Interlocked.Exchange(ref addonRequestCancellation, next);
        previous?.Cancel();
        return next;
    }

    private void ReleaseLoaderCancellation(CancellationTokenSource cancellation)
    {
        Interlocked.CompareExchange(ref loaderRequestCancellation, null, cancellation);
        cancellation.Dispose();
    }

    private void ReleaseAddonCancellation(CancellationTokenSource cancellation)
    {
        Interlocked.CompareExchange(ref addonRequestCancellation, null, cancellation);
        cancellation.Dispose();
    }

    private bool IsLoaderRequestCurrent(
        CancellationTokenSource cancellation,
        DownloadLoaderOption loaderOption,
        string minecraftVersion)
    {
        return ReferenceEquals(loaderRequestCancellation, cancellation)
            && ReferenceEquals(SelectedLoaderOption, loaderOption)
            && string.Equals(selectedMinecraftVersion?.Name, minecraftVersion, StringComparison.Ordinal)
            && isActive;
    }

    private bool IsAddonRequestCurrent(
        CancellationTokenSource cancellation,
        DownloadLoaderOption loaderOption,
        string minecraftVersion)
    {
        return ReferenceEquals(addonRequestCancellation, cancellation)
            && ReferenceEquals(SelectedLoaderOption, loaderOption)
            && string.Equals(selectedMinecraftVersion?.Name, minecraftVersion, StringComparison.Ordinal)
            && isActive;
    }

    private void ResetLoaderVersionState(bool cancelRequest = true)
    {
        if (cancelRequest)
        {
            var cancellation = Interlocked.Exchange(ref loaderRequestCancellation, null);
            cancellation?.Cancel();
        }
        LoaderVersions.Clear();
        SelectedLoaderVersion = null;
        IsLoadingLoaderVersions = false;
        LoaderVersionLoadError = string.Empty;
        OnPropertyChanged(nameof(LoaderVersionPlaceholderText));
    }

    private void ResetAddonLibraryVersionState(bool cancelRequest = true)
    {
        if (cancelRequest)
        {
            var cancellation = Interlocked.Exchange(ref addonRequestCancellation, null);
            cancellation?.Cancel();
        }
        IsLoadingAddonLibraryVersions = false;
        AddonLibraryVersionLoadError = string.Empty;
        ClearAddonLibraryVersionOptions();
    }

    private void ClearAddonLibraryVersionOptions()
    {
        AddonLibraryVersions.Clear();
        SelectedAddonLibraryVersion = null;
    }

    private void CancelRequests()
    {
        var loaderCancellation = Interlocked.Exchange(ref loaderRequestCancellation, null);
        loaderCancellation?.Cancel();
        var addonCancellation = Interlocked.Exchange(ref addonRequestCancellation, null);
        addonCancellation?.Cancel();
    }

    private void NotifyLoaderCollectionChanged()
    {
        OnPropertyChanged(nameof(HasLoaderVersions));
        OnPropertyChanged(nameof(HasNoLoaderVersions));
        OnPropertyChanged(nameof(LoaderVersionPlaceholderText));
    }

    private void NotifyAddonCollectionChanged()
    {
        OnPropertyChanged(nameof(HasAddonLibraryVersions));
        OnPropertyChanged(nameof(IsAddonLibraryVersionSelectorEnabled));
        OnPropertyChanged(nameof(AddonLibraryVersionPlaceholderText));
        NotifyQuiltLibraryAliasPropertiesChanged();
    }

    private void NotifyQuiltLibraryAliasPropertiesChanged()
    {
        OnPropertyChanged(nameof(QuiltLibraryVersions));
        OnPropertyChanged(nameof(SelectedQuiltLibraryVersion));
        OnPropertyChanged(nameof(HasQuiltLibraryVersions));
        OnPropertyChanged(nameof(HasQuiltLibraryVersionLoadError));
        OnPropertyChanged(nameof(IsQuiltLibraryVersionSelectorEnabled));
        OnPropertyChanged(nameof(IsLoadingQuiltLibraryVersions));
        OnPropertyChanged(nameof(QuiltLibraryVersionPlaceholderText));
        OnPropertyChanged(nameof(QuiltLibraryVersionLoadError));
    }

    private void NotifyStateChanged()
    {
        OnPropertyChanged(nameof(CanInstall));
        InstallAvailabilityChanged?.Invoke();
    }

    private static bool RequiresLoaderVersionSelection(LoaderKind? loaderKind)
    {
        return loaderKind is LoaderKind.Fabric or LoaderKind.Forge or LoaderKind.NeoForge or LoaderKind.Quilt;
    }

    private static bool SupportsAddonLibrarySelection(LoaderKind? loaderKind)
    {
        return loaderKind is LoaderKind.Fabric or LoaderKind.Quilt;
    }
}
